---
- name: Wait for ssh connection
  hosts: all
  gather_facts: False
  tasks: 
    - name: Ensure ssh port open
      ansible.builtin.wait_for:
        port: 22
        delay: 10
        timeout: 100
        search_regex: OpenSSH
        host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
      vars:
        ansible_connection: local


- name: Install Python3, Docker, docker-compose
  hosts: all
  become: yes
  gather_facts: False
  tasks:
    - name: Make sure python3 and docker are installed
      vars:
        ansible_python_interpreter: /usr/bin/python
      yum:
        name: 
          - python3
          - docker
        update_cache: yes
        state: present

    - name: Install Docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/latest/download/docker-compose-Linux-{{lookup('pipe', 'uname -m')}}
        dest: /usr/local/bin/docker-compose
        mode: +x

    - name: Ensure docker is running
      systemd:
        name: docker
        state: started

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes
        
    - name: Reconnect to server session
      meta: reset_connection

    - name: Install docker python module
      pip:
        name:
          - docker
          - docker-compose

- name: Start docker container
  hosts: all
  vars_files:
    - project-vars
  tasks:
    - name: Copy docker compose
      copy:
        src: /home/hichem-gh/Bureau/Terraform/apps/docker-compose.yaml
        dest: /home/ec2-user/docker-compose.yaml
    - name: Docker login
      docker_login:
        registry_url: https://index.docker.io/v1/
        username: ghazouanihm
        password: "{{docker_password}}"
    - name: Start container from compose
      docker_compose:
        project_src: /home/ec2-user
        state: present # docker-compose up